name: Sync Labels

on:
  push:
    branches:
      - main
    paths:
      # The labels file
      - labels.yml
      # This workflow
      - .github/workflows/sync-labels.yaml

  workflow_dispatch:

jobs:
  get-repos:
    name: Get Repos
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.get-repos.outputs.repos }}
    steps:
      - name: Get repository list
        id: get-repos
        uses: raven-actions/get-repos@v1
        with: 
          github-token: ${{ secrets.LABEL_SYNC_TOKEN_GITHUB }}

  sync-repo-labels:
    name: Sync ${{ matrix.repo.name }} labels
    runs-on: ubuntu-latest
    needs:
      - get-repos
    strategy:
      matrix:
        repo: ${{ fromJson(needs.get-repos.outputs.repos) }}
      fail-fast: false      
    steps:
      - name: Display matrix.repo information
        run: |
          echo "Archived: ${{ !matrix.repo.archived }}"
          echo "Repo: ${{ !matrix.repo.full_name }}"
          
      - name: Checkout .github repo (containing labels.yml)
        if: ${{ !matrix.repo.archived }} # Make sure repo is not archived
        uses: actions/checkout@v3

      - name: Sync labels (skip archived)
        if: ${{ !matrix.repo.archived }} # Make sure repo is not archived
        uses: brpaz/action-label-syncer@0.2.0
        with:
          manifest: labels.yml
          prune: true
          token: ${{ secrets.LABEL_SYNC_TOKEN_GITHUB }}
          repository: |
            ${{ matrix.repo.full_name }}

